# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Pull docker StrikeOne
        run: docker pull strike1/execute-vm-test:latest

      # Runs a set of commands using the runners shell
      - name: Execute test
        run: |
          docker run --rm -v $(pwd)/so_config/config.ini:/app/config.ini strikeone/execute_vm_test:latest python execute_test.py -ut $SO_TOKEN -tn test_dep_check -an $GITHUB_REPOSITORY -tt sast -t dep_check -url https://$GH_TOKEN@github.com/aleHRevirtus/project_with_jwt_vulnerable.git -pn $GITHUB_REPOSITORY -pb main
